title: å›½é™…ä¼ ç»Ÿå¤ªææ‹³å¥åº·ç ”ä¿®ä¸­å¿ƒ
author:
email: taichihealth.life@gmail.com
logo: _static/images/taiji_logo.PNG
copyright: "2022 å›½é™…ä¼ ç»Ÿå¤ªææ‹³å¥åº·ç ”ä¿®ä¸­å¿ƒ - ä¿®å¤ªæğŸ˜€äº«å¥åº·ğŸ˜€åŒå¿«ä¹" 
repository:
  url                       : https://github.com/wcj365/taiji
  path_to_book              : docs

latex:
  use_jupyterbook_latex: true
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks         : force  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

html:
  favicon                   : ""  # A path to a favicon image
  navbar_number_sections    : false  # Add a number to each section in your left navbar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  extra_navbar              : <a href="https://www.facebook.com/taiji74" target="_blank"><img src="_static/images/facebook.PNG" alt="facebook"></a> <a href="https://www.youtube.com/@taiji74" target="_blank"><img src="_static/images/youtube.png" alt="youtube"></a><a href="https://www.linkedin.com/company/taiji" target="_blank"><img src="_static/images/linkedin.PNG" alt="LinkedIn"></a>
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://taichihealth.life"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  search_bar_text           : "Search this website..."

launch_buttons:
  jupyterhub_url            : https://colab.research.google.com
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    language: zh_CN
    html_search_language: zh_CN    # make sure to pip install jieba3k
    latex_elements:
      fncychap: \usepackage[UTF8]{ctex}
