title: å¾·å¥‡å¤ªæ
author: <a href="mailto:wcj365@gmail.com" target="_blank">International Center for Tai Chi Health (ICTCH)</a>
email: wcj365@gmail.com
logo: _static/images/taiji_logo.png
copyright: "2022 å›½é™…ä¼ ç»Ÿå¤ªææ‹³å¥åº·ç ”ä¿®ä¸­å¿ƒ" 
repository:
  url                       : https://github.com/wcj365/taiji
  path_to_book              : docs

latex:
  use_jupyterbook_latex: true
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks         : force  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

html:
  favicon                   : "_static/images/taiji_logo.png"  # A path to a favicon image
  navbar_number_sections    : false  # Add a number to each section in your left navbar
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  extra_navbar              : "ä¿®å¤ªæğŸ˜€äº«å¥åº·ğŸ˜€åŒå¿«ä¹<br><br><a href="https://www.youtube.com/@taiji74">ææ²¹ç®¡é¢‘é“</a>"  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://taiji.pythonanywhere.com"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  search_bar_text           : ""

launch_buttons:
  jupyterhub_url            : https://colab.research.google.com
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    language: zh_CN
    html_search_language: zh_CN    # make sure to pip install jieba3k
    latex_elements:
      fncychap: \usepackage[UTF8]{ctex}
